version: 2.1

parameters:
  run_workflow_test:
    default: false
    type: boolean

jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "This is the build job"

  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "This is the test job"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          when: << pipeline.parameters.run_workflow_test >>
